export enum ApplicationNames {
  APPLE_MUSIC_NG = 'Apple Music NG',
  APPLE_MUSIC_USD = 'Apple Music USD',
  YOUTUBE_PREMIUM = 'Youtube Premium',
  iCLOUD = 'iCloud + 200GB',
  NORD_VPC = 'Nord VPN',
  EXPRESS_VPN = 'Express VPN',
  PIA_VPN = 'PIA VPN',
  SHOWMAX = 'ShowMax',
  APPLE_MUSIC_AND_iCLOUD_PLUS = 'Apple Music & iCloud+',
  iCLOUD_PLUS_200GB_USA = 'iCloud+ 200GB USA',
  NETFLIX_ULTRAHD = 'Netflix ULTRAHD',
  CANVA = 'Canva',
  IP_VANISH = 'IP Vanish',
  CRUNCHY_ROLL = 'Crunchyroll',
  SURF_SHARK = 'SurfShark',
}
