name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: enhanced-watch-413121
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true


    - name: Build Docker Image
      run: |
        docker build -t gcr.io/enhanced-watch-413121/subby-backend-image:latest .

    - name: Push Docker Image to GCR
      run: |
        docker push gcr.io/enhanced-watch-413121/subby-backend-image:latest