name: Build and Deploy to GCP

on:
  push:
    branches:
      - dev-revamp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: enhanced-watch-413121
      GCE_INSTANCE: your-instance-name

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Debug logging
      run: |
        echo "Service account key file content:"
        cat ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Authenticate with gcloud
      run: gcloud auth activate-service-account --key-file=${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Set IAM Policy Binding
      run: |
        gcloud projects add-iam-policy-binding ${{ env.PROJECT_ID }} \
          --member="serviceAccount:compute@developer.gserviceaccount.com" \
          --role="roles/artifactregistry.reader" \
          --role="roles/artifactregistry.writer"

    - name: Push Docker Image to GCR
      run: |
        gcloud auth configure-docker 
        docker push gcr.io/${{ env.PROJECT_ID }}/subby-backend-image:latest

    - name: Deploy to GCE
      run: |
        gcloud compute instances create-with-container ${{ env.GCE_INSTANCE }} \
          --image-family=cos-stable \
          --image-project=cos-cloud \
          --boot-disk-size=2GB \
          --boot-disk-type=pd-standard \
          --container-image=gcr.io/${{ env.PROJECT_ID }}/subby-backend-image:latest \
          --container-privileged \
          --zone=us-east1-c
